### ISSUE TITLE
Abstract FileReader

### ISSUE THREAD

**Issue by lrmoorejr** [dart-browser/universal_html#3]
This is fantastic work, thank you!  

Do you intend to flesh-out FileReader at some point?  It is the only missing piece to support uploading local files through a web-flutter app, which I suspect will be fairly common scenario.

(https://stackoverflow.com/questions/56457214/is-there-any-plugin-or-way-to-upload-file-to-server-using-flutter-web)

**Comment by terrier989** [comment]
Thank you!

The library already has a FileReader. However, the package can't access Flutter APIs because the package must work in the server-side too (without Flutter). So the proposed feature would have to be implemented in some other package.
